#!/bin/bash

usage() {
  echo "usage: ${0} -l | -a <domain> | -d <domain>"
}

if [ -x ${SCRIPT_DIR}/db_functions ]; then
  source ${SCRIPT_DIR}/db_functions
else
  echo "ERROR: Database Functions not found!"
  exit 255;
fi

# Analyse Commandline
RET=0
while getopts ":hla:d:" OPTION; do
  case ${OPTION} in
    l)
      list_domains; RET=$?;
      ;;
    a)
      domain_add ${OPTARG}; RET=$?;
      ;;
    d)
      domain_delete ${OPTARG}; RET=$?;
      ;;
    h)
      usage;
      exit 0;
      ;;
    :)
      log 0 "Missing Argument for option <${OPTION}>!";
      usage;
      exit 200;
      ;;
    \?)
      log 0 "Invalid Option <${OPTION}>";
      usage;
      exit 201;
      ;;
  esac
done

exit ${RET}

